FROM debian
LABEL maintainer="adespina@student.21-school.ru"
RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y vim && \
	apt-get install -y gcc && \
	apt-get install -y git

# How to build it?
# docker build -t b01 .

# How to run it?
# docker run --rm --name adespina_easy_container -ti b01
