FROM alpine
LABEL maintainer="adespina@student.21-school.ru"
RUN apk update && \
    apk upgrade && \
	    apk add vim
ENTRYPOINT vim

# How to build it?
# docker build -t ex00 .

# How to run it?
# docker run --rm -ti ex00

# How to know who author?
# docker inspect ex00
