#!/bin/sh
#Launch the hello-world container, and make sure that it prints its welcome message, then leaves it.
docker stop Char
docker start Char
docker logs -f Char
docker ps
docker ps -a
docker rm Char
