#!/bin/sh
#From the shell of a debian container, install via the container’s package manager everything you need to compile C source code and push it onto a git repo (of course, make sure before that the package manager and the packages already in the container are updated). For this exercise, you should only specify the commands to be run directly in the container.
#docker run -ti --rm debian (start Debian conainer)
apt update -y && apt upgrade -y
apt install gcc -y && apt install vim -y
apt install build-essential git -y or apt install git -y
# build-essential contains a list of packages which are essential for building Ubuntu packages including gcc compiler, make and other required tools.
